dependencies:
  build:
   - maven:3.5.4
   - java:11.0.8

build_targets:
  - name: default
    environment:
      - DEBIAN_FRONTEND=noninteractive
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - apt -y update
      - apt -y install libxtst6 libxi6
      - mvn package
ci:
  builds:
    - name: default
      build_target: default
